version: '2.1'

services:

  # App
  backend-dev:
           
    hostname: ${COMPOSE_PROJECT_NAME}

    container_name: ${COMPOSE_PROJECT_NAME}  
           
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        P_UID: ${P_UID}
        P_GID: ${P_GID}       
    
    image: ${COMPOSE_PROJECT_NAME}/golang:1.8.1-alpine           

    restart: ${RESTART}
    
    environment:   
      VIRTUAL_HOST: ${VIRTUAL_HOST} 
                      
    networks:
      - shared     
  
networks:
  shared:
    external:
      name: shared 